---
- hosts: all

  tasks:

  - stat:
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-base-v2/.git"
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme/.git"
    register: theme

  - name: Checkout WordCamp MU Plugin from SVN
    subversion:
      repo: https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/mu-plugins/"
    ignore_errors: yes

  - name: Checkout camptix-network-tools plugin from SVN
    subversion:
      repo: https://plugins.svn.wordpress.org/camptix-network-tools/trunk
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/camptix-network-tools"
    ignore_errors: yes

  - name: Checkout email-post-changes plugin from SVN
    subversion:
      repo: https://plugins.svn.wordpress.org/email-post-changes/trunk
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/email-post-changes"
    ignore_errors: yes

  - name: Checkout tagregator plugin from SVN
    subversion:
      repo: https://plugins.svn.wordpress.org/tagregator/trunk
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/tagregator"
    ignore_errors: yes

  - name: Checkout WordCamp Redux v2 Theme from SVN
    subversion:
      repo: https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/themes/wordcamp-base-v2/
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-base-v2"
    ignore_errors: yes

  - name: wp plugins activate
    command: "wp plugin activate camptix-network-tools"
    command: "wp plugin activate email-post-changes"
    command: "wp plugin activate tagregator"

  - name: Clone Your WordCamp Theme from Git
    when: theme.stat.exists != true
    git:
      repo: https://github.com/YOUR-WORDCAMP-ORGANIZATION-NAME/YOUR-WORDCAMP-THEME-REPOSITORY-NAME.git
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme"
      version: develop

  - name: wp theme activate
    command: "wp theme activate wordcamp-base-v2"

  - name: Import Your WordCamp Posts
    command: "wp import {{ vccw.vagrant_dir }}/YOUR-WORDCAMP-POST.xml --authors=create"


