---
- hosts: all

  tasks:

  - stat:
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-base-v2/.git"
    register: theme

  - stat:
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme/.git"
    register: theme

  - name: Checkout WordCamp MU Plugin from SVN
    subversion:
      repo: https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/mu-plugins/"
    ignore_errors: yes

  - name: Checkout WordCamp Plugin from SVN
    vars:
      wc_plugins: [
        # bbpress-network-templates,
        camptix-admin-flags,
        camptix-attendance,
        camptix-badge-generator,
        camptix-mailchimp,
        email-post-changes-specific-post,
        jquery-ui-css,
        # multi-event-sponsors,
        wc-canonical-years,
        wc-fonts,
        wc-post-types,
        wcpt,
        wordcamp-api,
        wordcamp-coming-soon-page,
        wordcamp-dashboard-widgets,
        wordcamp-docs,
        # wordcamp-forms-to-drafts,
        # wordcamp-mentors,
        # wordcamp-organizer-reminders,
        wordcamp-participation-notifier,
        wordcamp-payments,
        wordcamp-payments-network,
        # wordcamp-qbo,
        # wordcamp-qbo-client,
        wordcamp-remote-css,
        wordcamp-reports,
        wordcamp-site-cloner,
        wordcamp-spreadsheets,
        wordcamp-wiki
      ]
    subversion:
      repo: https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/plugins/{{ item }}
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/{{ item }}"
    with_items:
      - "{{ wc_plugins }}"
    ignore_errors: yes

  - name: Checkout plugin from SVN
    vars:
      wp_plugins: [
        camptix-network-tools,
        email-post-changes
      ]
    subversion:
      repo: https://plugins.svn.wordpress.org/{{ item }}/trunk
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/{{ item }}"
    with_items:
      - "{{ wp_plugins }}"
    ignore_errors: yes

  - name: Checkout Camptix plugin from Git
    when: theme.stat.exists != true
    git:
      repo: https://github.com/Automattic/camptix.git
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/camptix"
      version: master

#  - name: Checkout tagregator plugin from SVN
#    subversion:
#      repo: https://plugins.svn.wordpress.org/tagregator/trunk
#      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/plugins/tagregator"
#    ignore_errors: yes

  - file: path={{ vccw.vagrant_dir }}/wordpress/wp-content/mu-plugins/wcorg-login-message.php state=absent

  - name: Checkout WordCamp Redux v2 Theme from SVN
    subversion:
      repo: https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/themes/wordcamp-base-v2/
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-base-v2"
    ignore_errors: yes

  - name: Activate camptix-network-tools
    command: "wp plugin activate camptix-network-tools --network"

  - name: Activate email-post-changes
    command: "wp plugin activate email-post-changes --network"

  - name: Activate Tagregator
    command: "wp plugin activate tagregator --network"

  - name: Clone Your WordCamp Theme from Git
    when: theme.stat.exists != true
    git:
      repo: https://github.com/wcosaka2018/wcosaka2018-theme.git
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wcosaka2018-theme"
      version: master # Select Branch

  - name: Activate theme
    command: "wp theme enable wcosaka2018-theme --network"

  - name: Import your WordCamp posts
    command: "wp import {{ vccw.vagrant_dir }}/wordcamposaka2018.wordpress.2018-02-20.xml --authors=create"

  - name: Activate all plugin
    command: "wp plugin activate --all"

  - name: Deactivate plugin
    command: "wp plugin deactivate akismet"

  - name: Deactivate plugin
    command: "wp plugin uninstall Hello"
