---
- hosts: all

  tasks:

  - stat:
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme/.git"
    register: theme

  - name: Clone Theme
    when: theme.stat.exists != true
    git:
      repo: https://github.com/jawordpressorg/wordcamp-japan-theme.git
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme"

  - name: wp theme activate
    command: "wp theme activate wordcamp-japan-theme"


