---
- include: provision/playbook-wordcamp.yml

- hosts: all

  tasks:

 # multisite Settings
  - name: Run `wp core multisite-convert`
    command: |
      wp core multisite-convert --subdomains
      --path={{ path }}
  - name: Create `.htaccess` for multisite
    when: vccw.multisite
    template:
      src: templates/multisite-htaccess
      dest: /tmp/.htaccess
  - name: Move `.htaccess` for multisite
    command: "mv /tmp/.htaccess {{ vccw.document_root }}/.htaccess"
  - name: Setting up Wordpress multisite options
    command: |
      wp network meta update 1 {{ item.key }} '{{ item.value }}'
      --path={{ path }}
    with_dict: "{{ vccw.multisite_options | default({}) }}"

  # Set git init Your WordCamp theme Directory.
  - stat:
      path: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wordcamp-japan-theme/.git" # Assign directory.
    register: theme

  # Git clone your WordCamp theme repository.
  - name: Install Your WordCamp Theme from Git
    when: theme.stat.exists != true
    git:
      repo: https://github.com/wcosaka2018/wcosaka2018-theme.git # Set repository.
      dest: "{{ vccw.document_root }}/{{ vccw.wp_siteurl }}/wp-content/themes/wcosaka2018-theme" # Assign directory.
      version: master # Select Branch.

  - name: Activate theme
    command: "wp theme enable wcosaka2018-theme --activate"

  # Import your WordCamp posts data(XML).
  - name: Import your WordCamp posts
    command: "wp import {{ vccw.vagrant_dir }}/wordcamposaka2018.wordpress.2018-02-20.xml --authors=create" # set posts xml file.
