---
- hosts: all

  tasks:

  - name: Clone Theme
    git:
      repo: https://github.com/jawordpressorg/wordcamp-japan-theme.git
      dest: "{{ vccw.document_root }}/wp-content/themes/wordcamp-japan-theme"

  - name: wp theme activate
    command: "wp theme activate wordcamp-japan-theme"


