# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: japan.wordcamp.test
ip: 192.168.108.108

#
# WordPress Settings
#
version: latest
lang: ja
title: WordCamp Japan
rewrite_structure: /%year%/%monthnum%/%day%/%postname%/


#
# WordPress User
#
admin_user: vccw
admin_pass: vccw
admin_email: wcj@japan.wordcamp.test

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins: [
  gutenberg
]

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: 'twentyfifteen'

#
# WordPress Options
#
options:
  blogdescription: 'WordPress イベント「WordCamp」の日本語公式サイト'

#
# Theme unit testing
#
theme_unit_test: true
theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# DB will be reset when provision
#
reset_db_on_provision: true

#
# RubyGems
# Wordmove will be forcibly installed.
#
ruby_gems: []

mailcatcher: false

wp_i18n_tools: true

#
# NPM modules
#
npms: []

#
# composer
#
composers: []

#
# wp-cli package commands
#
wp_cli_packages: []

#
# Linked Clone for Vagrant v1.8
#
linked_clone: true
